### PR TITLE
Update dependencies and deprecated code

### PR DESCRIPTION
**Pull request by wuan**

### CODE REVIEW

**Review by hacklschorsch — APPROVED** [review]
Disclaimer: I have almost no Android/Kotlin experience.

The changes look good to me though, it's mostly version updates and some code that doesn't look like it has many logic changes and I trust is mostly required by the library updates?

**Comment by wuan** [comment]
Yes, they have replaced referencing the UI frames with a different code generating framework.

**Comment by wuan** [comment]
Thanks @hacklschorsch for taking the time for a review.

**Comment by hacklschorsch** [comment]
wild

This is awesome! Please merge away!

**Comment by wuan** [comment]
I'm sorry sir @hacklschorsch. I would like to do so, but I fear I'm not authorized to perform that action.

**Comment by hacklschorsch** [comment]
Uh! Thanks for clarifying. Neither am I. Will call for help.

**Comment by crwood** [comment]
Neither am I... Perhaps @ewanas can do this (and/or grant appropriate access to others)?

**Comment by hacklschorsch** [comment]
Thanks!

Dancing Dog

**Pull request merged**
